## Required parameters
model_type: "fasttext"
saved_dir: "./output/FastText"
train_path: "./dataset/query_wellformedness/train.txt"
test_path: "./dataset/query_wellformedness/test.txt"
pretrained_embedding: null #"./resources/glove.6B.300d.txt"
pretrained_model_dir: null
data_format: ['text', 'label']
delimiter: '\t'


max_len: 256
pad_token: "<pad>"
unk_token: "<unk>"

embed_dim: 10
optim: 'sgd'
num_epoch: 100
lr: 0.5
momentum: 0.9
batch_size: 128
decay_rate: 0.9
decay_steps: -1 # if = -1 update after each epoch
valid_interval: 1
random_seed: 64

device: "cuda"