## Required parameters
model_type: "fasttext"
saved_dir: "./output/FastText"
train_path: "./dataset/ag_news/processed_train.csv"
test_path: "./dataset/ag_news/processed_test.csv"
pretrained_embedding: null #"./resources/glove.6B.300d.txt"
pretrained_model_dir: null
data_format: ['text', 'label']
delimiter: '\t'


max_len: 256
pad_token: "<pad>"
unk_token: "<unk>"

embed_dim: 300
hidden_dim: 10
optim: 'sgd'
num_epoch: 100
lr: 0.001
momentum: 0.9
batch_size: 128
valid_interval: 1
random_seed: 64

device: "cuda"