## Required parameters
model_type: "transformer"
saved_dir: "./output/Transformer/"
train_path: "./dataset/query_wellformedness/train.txt"
test_path: "./dataset/query_wellformedness/test.txt"
pretrained_model_dir: null
data_format: ['text', 'label']
delimiter: '\t'

max_len: 60
pad_token: "<pad>"
unk_token: "<unk>"

hidden_dim: 256
inter_dim: 1024
num_layers: 6
num_heads: 8
dropout_prob: 0.1


optim: 'sgd'
num_epoch: 100
lr: 0.001
momentum: 0.9
batch_size: 64
valid_interval: 1
random_seed: 64
decay_rate: 0.9
decay_steps: -1 # if = -1 update after each epoch


device: "cuda"